### ISSUE TITLE
Loader Problem

### ISSUE THREAD

**Issue by musaghauri** [halt-hammerzeit/libphonenumber-js#10]
![screenshot 2017-01-10 17 53 57](https://cloud.githubusercontent.com/assets/13300306/21806945/09273590-d75e-11e6-8594-47b1024b2fe9.png)

I am just importing parse and asyoutype!
And this is the error I get while compiling!
I have added json-loader as suggested but still the problem persists!

**Comment by halt-hammerzeit** [comment]
I confirm this bug.
Will be fixed today.

**Comment by halt-hammerzeit** [comment]
Try the newest version, it should work

**Comment by musaghauri** [comment]
![screenshot 2017-01-10 19 19 26](https://cloud.githubusercontent.com/assets/13300306/21809500/d4c1d1dc-d769-11e6-9e12-eb3dd346fa78.png)
This issue still persists! Loader issue resolved!

**Comment by halt-hammerzeit** [comment]
Well, `metadata.min` is there:
https://unpkg.com/libphonenumber-js@0.2.28/
If you override `resolve.extensions` in Webpack configuration then make sure `.json` extension is present in the list.
Most likely it isn't in your case.
