### ISSUE TITLE
PK country code not working!

### ISSUE THREAD

**Issue by musaghauri** [halt-hammerzeit/libphonenumber-js#11]
in asyouwrite, PK country code is not working!

**Comment by halt-hammerzeit** [comment]
What do you mean by "PK country code is not working!"

**Comment by musaghauri** [comment]
I am using PK => Pakistan in country code! And it's not formatting as expected!

**Comment by musaghauri** [comment]
but working fine in format!

**Comment by halt-hammerzeit** [comment]
Give me the specifics.
What exactly are you entering on the demo page, what is the expected result, what is the actual result, and does it even work in the reference Google's demo.

**Comment by musaghauri** [comment]
I got it! It doesn't handle mobile numbers I guess! In demo, it is only handling landline numbers!

**Comment by halt-hammerzeit** [comment]
For any bug, if it works in Google's demo and doesn't work in this project's demo, then create an issue here.
Otherwise, if it doesn't work in Google's demo, then create an issue in Google's repo.

**Comment by musaghauri** [comment]
I am sorry for any inconvenience!
