### ISSUE TITLE
bundle/browser build gives error `libphonenumber is not defined`

### ISSUE THREAD

**Issue by clindsey** [halt-hammerzeit/libphonenumber-js#14]
I'm trying to use this in the browser on [codepen.io](https://codepen.io), but when I try to use the library with `libphonenumber-js`, it gives me an error `Uncaught RferenceError: libphonenumber is not defined`.  It works if I instead do `window['libphonenumber-js'].asYouType`.

The name `libphonenumber-js` is a strange name to use in browser javascript.  I get that it works well with es6 imports `import {asYouType} from 'libphonenumber-js';`; is there any way to support `LibPhoneNumberJS` in the browser build?

**Comment by halt-hammerzeit** [comment]
Try the new version

**Comment by halt-hammerzeit** [comment]
Yeah, forgot to `npm publish`. Now available
https://unpkg.com/libphonenumber-js@0.2.31/bundle/libphonenumber-js.min.js
