### ISSUE TITLE
angular2 and SystemJS import

### ISSUE THREAD

**Issue by tommathias** [halt-hammerzeit/libphonenumber-js#15]
After installing through npm in my angular 2 app and updating my SystemJS config.ts to include

`'libphonenumber-js': 'npm:angular-libphonenumber/index.es6.js'`

and including 
`import { parse, format, asYouType } from 'libphonenumber-js';` in my @Directive and @NgModule, I'm still getting "Cannot find module 'libphonenumber-js'"

Do I need to do anything else specific to install this into my ng2 app?

**Comment by halt-hammerzeit** [comment]
I haven't dealt with Angular 2 but I know that, for example, when using Webpack 2 or Babel one can write it like this:

```js
import { parse, format, asYouType } from 'libphonenumber-js';
```

It is possible that Angular 2 has its own ES6 module parser/compiler/bundler/whatever else.
But that's out of the scope of this library.
Anything will do as long as it sticks to ES2015 `import` standard.
