### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by aloisdg** [halt-hammerzeit/libphonenumber-js#3]
Hello,

If the lib is ready to use, could you release one?

Thank you

Cheers,

**Comment by halt-hammerzeit** [comment]
Hello.
Of course it is ready, why wouldn't it be?
What's the source of your confusion?

**Comment by halt-hammerzeit** [comment]
Oh, you mean the `releases` tab?
https://github.com/halt-hammerzeit/libphonenumber-js/releases
I don't see the point of this tab.
I have releases in npm, just do `npm install libphonenumber-js --save`

**Comment by aloisdg** [comment]
What if I cant or dont want to use npm?

**Comment by halt-hammerzeit** [comment]
What are you using then?

**Comment by aloisdg** [comment]
Nothing. Well http, a browser and softwares my IT service allow me to use.

**Comment by halt-hammerzeit** [comment]
Why aren't you using Webpack or Browserify?
It's modern software.

You can build a bundle yourself: clone the repo, `npm install`, `npm run browser-build`, and see the `bundle` directory.

**Comment by aloisdg** [comment]
> Why aren't you using Webpack or Browserify?

Why cant I just download a `libphonenumber.min.js` and deal with it?

> It's modern software.

Thats not the point.

> You can build a bundle yourself: clone the repo, npm install, npm run browser-build, and see the bundle directory.

 I will have to install node.

**Comment by halt-hammerzeit** [comment]
> I will have to install node.
> Why cant I just download a libphonenumber.min.js and deal with it?

You can, if you don't have Node.js.
I can compile it for you, but it won't be the latest version though.
Anyway, I'll release it, ok.

> Thats not the point.

Yeah, that's the point: the guys not letting you use Webpack aren't that smart.

**Comment by aloisdg** [comment]
Thank you!

**Comment by halt-hammerzeit** [comment]
Ok, so I'm not sure if it's gonna work, but try this
https://github.com/halt-hammerzeit/libphonenumber-js/releases/tag/0.2.1
And report back

**Comment by aloisdg** [comment]
@halt-hammerzeit Works perfectly. Live demo on [Plunker](http://plnkr.co/edit/7XoUUXDq0JERIeUluyQR?p=preview).

**Comment by kohenkatz** [comment]
@aloisdg In the future, you can also use [UNPKG](https://unpkg.com/#/) to download the built code from NPM.

For example: https://unpkg.com/libphonenumber-js@0.2.27/bundle/libphonenumber-js.min.js

You can leave out the `@VERSION_NUMBER` from the URL to get the latest version, whatever it happens to be.
