### ISSUE TITLE
Different result for asyoutype and format

### ISSUE THREAD

**Issue by ua9msn** [halt-hammerzeit/libphonenumber-js#35]
For number +4915539898001
asYouType returns +49 155 39898001
Format International returns: +49 15539 898001
Should it be the same?

**Comment by halt-hammerzeit** [comment]
If you give me the step to reproduce this issue I can have a look.
EIther via [the demo](https://halt-hammerzeit.github.io/libphonenumber-js/) or via code.

**Comment by ua9msn** [comment]
At the demo page
1. Clear default country code in all fields
2. Copy the number and paste it into "as you type" and "format" phone fields
2a. The same result if you type the number one by one digit

**Comment by halt-hammerzeit** [comment]
Ok, this is confirmed

**Comment by halt-hammerzeit** [comment]
Thanks for the bug reports, the bugs has been fixed in the latest release.

**Comment by halt-hammerzeit** [comment]
@ua9msn Как ваще библиотека, норм? Или чего-то ещё нужно.
