### ISSUE TITLE
npm browser-build fails

### ISSUE THREAD

**Issue by anwa79** [halt-hammerzeit/libphonenumber-js#38]
When I build using npm for browser, I get the following error log. I can send over npm-debug.log if needed.
I tried installing various version of node/npm version combinations (including the latest).

> libphonenumber-js@0.3.3 browser-build \JS_LIB\libphonenumber-js
> npm run build-es6-modules && WEBPACK_ENV=build webpack

> libphonenumber-js@0.3.3 build-es6-modules \JS_LIB\libphonenumber-js
> better-npm-run build-es6-modules

running better-npm-run in \JS_LIB\libphonenumber-js
Executing script: build-es6-modules

to be executed: "babel ./source --out-dir ./es6 --source-maps"
source\as you type.js -> es6\as you type.js
source\common.js -> es6\common.js
source\format.js -> es6\format.js
source\metadata.js -> es6\metadata.js
source\parse.js -> es6\parse.js
source\tools\compress.js -> es6\tools\compress.js
source\tools\download.js -> es6\tools\download.js
source\tools\generate.js -> es6\tools\generate.js
source\validate.js -> es6\validate.js
'WEBPACK_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "browser-build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! libphonenumber-js@0.3.3 browser-build: `npm run build-es6-modules && WE
BPACK_ENV=build webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libphonenumber-js@0.3.3 browser-build script 'npm run bui
ld-es6-modules && WEBPACK_ENV=build webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libphonenumber-js pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-es6-modules && WEBPACK_ENV=build webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libphonenumber-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libphonenumber-js
npm ERR! There is likely additional logging output above.

**Comment by halt-hammerzeit** [comment]
The error is caused because it's Windows which can't understand Linux env variables.
I'll fix that.

**Comment by halt-hammerzeit** [comment]
Fixed via https://github.com/halt-hammerzeit/libphonenumber-js/commit/c7e52ec08280bb18f167ab3b42707c7d6329c777
Pull and retry.

**Comment by anwa79** [comment]
Thank you for the quick response.
I've given it another try but the "bundle" folder is not created after running command: npm run browser-build
No error though.

Here a CMD extract:

C:\JS_LIB02\libphonenumber-js>npm run browser-build

> libphonenumber-js@0.3.3 browser-build C:\JS_LIB02\libphonenumber-js
> better-npm-run browser-build

running better-npm-run in C:\JS_LIB02\libphonenumber-js
Executing script: browser-build

to be executed: "npm run build-es6-modules"

> libphonenumber-js@0.3.3 build-es6-modules C:\JS_LIB02\libphonenumber-js
> better-npm-run build-es6-modules

running better-npm-run in C:\JS_LIB02\libphonenumber-js
Executing script: build-es6-modules

to be executed: "babel ./source --out-dir ./es6 --source-maps"
source\as you type.js -> es6\as you type.js
source\common.js -> es6\common.js
source\format.js -> es6\format.js
source\metadata.js -> es6\metadata.js
source\parse.js -> es6\parse.js
source\tools\compress.js -> es6\tools\compress.js
source\tools\download.js -> es6\tools\download.js
source\tools\generate.js -> es6\tools\generate.js
source\validate.js -> es6\validate.js

C:\JS_LIB02\libphonenumber-js>

**Comment by halt-hammerzeit** [comment]
Oh, I forgot something.
Pull again.
