### ISSUE TITLE
The bundle folder for libphonenumber-js.min.js not created when running "npm run browser-build"

### ISSUE THREAD

**Issue by anwa79** [halt-hammerzeit/libphonenumber-js#39]
I've given it another try but the "bundle" folder is not created after running command: npm run browser-build
No error though. Just be sure, I'm trying to generate the standalone libphonenumber-js.min.js file.

Here a CMD extract:

C:\JS_LIB02\libphonenumber-js>npm run browser-build

    libphonenumber-js@0.3.3 browser-build C:\JS_LIB02\libphonenumber-js
    better-npm-run browser-build

running better-npm-run in C:\JS_LIB02\libphonenumber-js
Executing script: browser-build

to be executed: "npm run build-es6-modules"

    libphonenumber-js@0.3.3 build-es6-modules C:\JS_LIB02\libphonenumber-js
    better-npm-run build-es6-modules

running better-npm-run in C:\JS_LIB02\libphonenumber-js
Executing script: build-es6-modules

to be executed: "babel ./source --out-dir ./es6 --source-maps"
source\as you type.js -> es6\as you type.js
source\common.js -> es6\common.js
source\format.js -> es6\format.js
source\metadata.js -> es6\metadata.js
source\parse.js -> es6\parse.js
source\tools\compress.js -> es6\tools\compress.js
source\tools\download.js -> es6\tools\download.js
source\tools\generate.js -> es6\tools\generate.js
source\validate.js -> es6\validate.js

C:\JS_LIB02\libphonenumber-js>

**Comment by halt-hammerzeit** [comment]
Fixed

**Comment by halt-hammerzeit** [comment]
Fixed again, pull
