### ISSUE TITLE
Different output when parsing

### ISSUE THREAD

**Issue by aloisdg** [halt-hammerzeit/libphonenumber-js#4]
Hello,

I tried to check the validity of `+33169454850` like this:

    var libphonenumber = window['libphonenumber-js'];
    document.body.innerText = libphonenumber.isValidNumber('+33169454850');

[demo](http://plnkr.co/edit/7XoUUXDq0JERIeUluyQR?p=preview)

And got "false", but "true" when I try on the [official project demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html).

What did I miss?

Thank you!

**Comment by halt-hammerzeit** [comment]
Oh, that was a silly one.
Thx for the bug report, fixed.
Try the new release:
https://github.com/halt-hammerzeit/libphonenumber-js/releases/tag/0.2.2

**Comment by aloisdg** [comment]
You are welcome!
