### ISSUE TITLE
Why not export getNumberType ?

### ISSUE THREAD

**Issue by chafel** [halt-hammerzeit/libphonenumber-js#41]
`getNumberType` seems like a useful feature, I can see this function in [here](https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/source/parse.js#L589).

**Comment by halt-hammerzeit** [comment]
Closed via https://github.com/halt-hammerzeit/libphonenumber-js/commit/f44ed96fb20d174eebb0d091065ab6c170897cbd
Install the new version
