### ISSUE TITLE
Use a CDN

### ISSUE THREAD

**Issue by aloisdg** [halt-hammerzeit/libphonenumber-js#5]
Hello,

It would be nice to be able to use libphonenumber through a CDN (like [cdnjs](https://cdnjs.com/)).

What do you think?

**Comment by halt-hammerzeit** [comment]
Sure, what am I required to do for that?
There's a request library hyperlink on their website: I guess the library is to be requested first.
You could do that.
Dunno what's next.
Am I needed to put the `min` bundle to npm?

**Comment by aloisdg** [comment]
@halt-hammerzeit I dont know, but I can look for it.

**Comment by halt-hammerzeit** [comment]
Yeah, you could do that, when you have time

**Comment by aloisdg** [comment]
@halt-hammerzeit I opened an issue for now #9962

**Comment by halt-hammerzeit** [comment]
I created a Pull Request for that cdnjs.
https://github.com/cdnjs/cdnjs/pull/9963
Too complex.

**Comment by aloisdg** [comment]
indeed.

**Comment by halt-hammerzeit** [comment]
No response from them, so closing this issue.
