### ISSUE TITLE
Local swedish mobile phone numbers breaks the as you type formatter

### ISSUE THREAD

**Issue by mrlundis** [halt-hammerzeit/libphonenumber-js#51]
**Whats wrong**
Typing a local Swedish mobile phone number (with default country set to: SE) in the as you type formatter in the demo makes the caret move unexpectedly.

**How to reproduce**
Entering a valid local mobile phone number, for example the prefix 077 followed by 1234567. This leads to the number being formatted as `077-123 46 75`. The 5 is in the end instead of after 4.

The caret seems to jump when the dash-character moves and the spacing changes as you type 5. 

**Expected behaviour**
The number should be formatted as `077-123 45 67`.

**Comment by halt-hammerzeit** [comment]
Fixed in the new version.
Now it's just like https://libphonenumber.appspot.com does
