### ISSUE TITLE
Some GB numbers showing invalid

### ISSUE THREAD

**Issue by fivetentaylor** [halt-hammerzeit/libphonenumber-js#52]
This is a number I stumbled across while testing, it's for the Park Plaza Westminster Bridge London hotel and it shows as invalid
 
isValidNumber('+44 844 415 6790', 'GB') == false

**Comment by halt-hammerzeit** [comment]
Fixed in the new release.
Metadata for "shared cost" numbers wasn't generated correctly due to a typo
