### ISSUE TITLE
invalid format Ghana phone numbers

### ISSUE THREAD

**Issue by mikhail-angelov** [halt-hammerzeit/libphonenumber-js#54]
numbers like this:
233111111111
it formats like:
233 233111111111

//test
import { format } from 'libphonenumber-js'

it('Ghana phone',()=>{
  const phone = format('233111111111', 'GH', 'International')
  expect(phone).toBe('+233111111111')
})

**Comment by halt-hammerzeit** [comment]
How do you expect `233111111111` in international to be `+233111111111`.
That's nonsense

**Comment by mikhail-angelov** [comment]
233 - is country code, so I expect International phone format in, this case should be like
+233111111111 (the same as google-libphonenumber)
not
+233 233111111111 (current behavior)

**Comment by halt-hammerzeit** [comment]
Show me "same as google-libphonenumber" in the google-libphonenumber demo

**Comment by mikhail-angelov** [comment]
https://libphonenumber.appspot.com/phonenumberparser?number=233111111111&country=GH

**Comment by halt-hammerzeit** [comment]
And?
What's the international number on that page.

**Comment by mikhail-angelov** [comment]
ok, incorrect input, sorry
check out this link
https://libphonenumber.appspot.com/phonenumberparser?number=233244111111&country=GH

**Comment by mikhail-angelov** [comment]
import { format } from 'libphonenumber-js'

it('Ghana phone',()=>{
  const phone = format('233244111111', 'GH', 'International')
  expect(phone).toBe('+233244111111')
})
///-
   Expected value to be (using ===):
      "+233244111111"
    Received:
      "+233 233244111111"

**Comment by halt-hammerzeit** [comment]
ok, while `libphonenumber` parses `233244111111` as `+233244111111` I don't see any reason for doing that because if the international standard states that there **must be** a `+` sign then there must be `+` sign and I don't think it would be sane to try adding a `+` sign manually just to check if an invalid phone number can be parsed as an international one.

**Comment by mikhail-angelov** [comment]
ok, no problem.
