### ISSUE TITLE
Parse Options Issue

### ISSUE THREAD

**Issue by mluyties** [halt-hammerzeit/libphonenumber-js#55]
Your js version is fantastic so far, so thank you =) However, I'm running in to one issue where I'm trying to parse a phone number but don't want to force a country code. I'd like it to figure out based on what is typed. But when I create the options object and pass it in to parse, I get this error:

Uncaught TypeError: Cannot read property 'default' of undefined
    at e (libphonenumber-js.min.js:1)
    at new e (libphonenumber-js.min.js:4)

I've tried multiple ways to create an object with different values for your two fields:

var options = {};
options.restrict = '';
options.default = 'US';

Thanks, Mike

**Comment by halt-hammerzeit** [comment]
Learn how to format code on github

**Comment by halt-hammerzeit** [comment]
Don't pass the second argument and there will be no default country
