### ISSUE TITLE
asYouType() no response if no country code set

### ISSUE THREAD

**Issue by mluyties** [halt-hammerzeit/libphonenumber-js#56]
If I leave the country code blank asYouType() instead of asYouType('US'), it doesn't format for international numbers. I've tried asYouType('International') with same issue.

**Comment by halt-hammerzeit** [comment]
Give a code example and the expected output

**Comment by halt-hammerzeit** [comment]
Everything works, see the demo

**Comment by mluyties** [comment]
I've found the issue. The + must be included when the user types or it doesn't work. This also occurs on your demo if you remove the default country code and just type in a phone number without prepending the +

Thanks for your help.

**Comment by halt-hammerzeit** [comment]
Yes, it's by no means an issue, the plus sign must be prepended as per the international standards

**Comment by AlekseevI** [comment]
I've got the same issue 
```
import { asYouType } from 'libphonenumber-js';
const formatter = new asYouType();
formatter.input('1') // returns '1'
```
Most strange part is that you have the test for this case and it passes
https://github.com/catamphetamine/libphonenumber-js/blob/master/test/as%20you%20type.js#L51

Maybe I missed something.

**Comment by catamphetamine** [comment]
@AlekseevI What is the exact issue you're having

**Comment by AlekseevI** [comment]
I've got no formatting when passing no parameters to `AsYouType`. Is it normal behaviour?

**Comment by catamphetamine** [comment]
Post the exact code, the observed result and the expected result

**Comment by AlekseevI** [comment]
This code
```
import { asYouType } from 'libphonenumber-js';
const formatter = new asYouType();
formatter.input('1')
```
returns `'1'` and I was expecting `'+1'`

Is it normal that `asYouType` formatter does nothing when no `default_country_code` is specified? It does not guess format/country or something like that.

**Comment by catamphetamine** [comment]
Why did you even expect it to return `+1`

**Comment by AlekseevI** [comment]
Because it's international mode :) All numbers should start with '+'.
It was my bad I missed docs, I got that this behavior is not implemented. 
In my case I can replace '1' with '+1' for US - there is no area code which starts with 1.

Thanks for help! 
Sorry for bothering you

**Comment by catamphetamine** [comment]
> Because it's international mode

It doesn't say so.
If you think it does then provide the absract from the README.
