### ISSUE TITLE
Inconsistency between isValidNumber and the valid property of asYouType

### ISSUE THREAD

**Issue by AndreasZeiser** [halt-hammerzeit/libphonenumber-js#6]
Hey!

First of all thank you for providing this alternative to the official library provided by Google.

`isValidNumber()` returns `true` for the invalid german phone number '123456' while the `valid` property of `asYouType` returns `false` as expected/desired. `isValidNumber()` uses `parse()` internally which strips the national prefix.

If this behavior is desired then I believe it must be documented more clearly in the README.md.

**Comment by halt-hammerzeit** [comment]
Halo.

Yes, this seems to be a bug since Google doesn't recognise it as a valid phone number
https://libphonenumber.appspot.com/phonenumberparser?number=123456&country=DE

I'm looking into it.
Since you're German, what are your thoughts on what the reason might be?
National prefix is `0`, not `1`

**Comment by AndreasZeiser** [comment]
Ah sorry, I wasn't clear enough. `123456` is not a valid number since the national prefix is missing which is `0` for Germany. That's why I was surprised that `isValidNumber()` returns `true`.

Google got it right, their result of `isValidNumber()` is `false`.

**Comment by halt-hammerzeit** [comment]
Ok, I seem to have some clues on what the issue might be.
The reason for this library being small is because all the specific regular expressions are dropped, and that's where the number probably gets rejected in Google's `libphonenumber`.
I'm gonna extend metadata generation options to include those specific regular expressions and presumably after that it would work.

**Comment by halt-hammerzeit** [comment]
Try the new version.
It should return `false` in case of the `--extended` metadata (see the README)

**Comment by halt-hammerzeit** [comment]
(renamed `libphonenumber-js-update-metadata` to `libphonenumber-generate-metadata`)

**Comment by AndreasZeiser** [comment]
Hey Nikolay

If the national prefix is missing `asYouType` & `isValidNumber` still behave differently. Here is an example:

The national prefix in Germany is `0`. The phone number `30123456` is invalid because it's missing the national prefix. When using `asYouType.valid` and `isValidNumber` both must return `false` as the result but this is not the case.

```javascript
const phoneNumber = '30123456';

const isValidNumberCustomCountries = isValidNumber.bind({ metadata });
console.log(isValidNumberCustomCountries(phoneNumber, 'DE')); // true

const asYouTypeCustomCountries = asYouType(metadata);
const phoneNumberUtil = new asYouTypeCustomCountries('DE');
phoneNumberUtil.input(phoneNumber);
console.log(phoneNumberUtil.valid); // false
```

Note: I've used the metadata generated with the argument `--extended`.

**Comment by halt-hammerzeit** [comment]
Ok, so I guess it should be `false`.
Seems that `isValidNumber` currently only validates the national number and doesn't check the national prefix.
I'll add that check.

**Comment by halt-hammerzeit** [comment]
Fixed in this commit: https://github.com/halt-hammerzeit/libphonenumber-js/commit/f8d66065e87c965def8de8f1a8afa1c9cf0ef1ae
Try the new release.

**Comment by halt-hammerzeit** [comment]
Due to a recent issue I'm reverting this fix
https://github.com/halt-hammerzeit/libphonenumber-js/issues/67

"As you type" now no longer provides validation.
And `30123456 ` is considered **valid** by the official Google demo:
https://libphonenumber.appspot.com/phonenumberparser?number=30123456&country=DE
