### ISSUE TITLE
Failed running script liphonenumber-generate-metadata 

### ISSUE THREAD

**Issue by onlineautoparts** [halt-hammerzeit/libphonenumber-js#62]
Hi I'm trying to create a custom metadata but I get the following error:

`
```
root@ip-172-31-5-150:/home/ubuntu/libphonenumber-js# npm run-script libphonenumber-metadata

> libphonenumber-js@0.4.1 libphonenumber-metadata /home/ubuntu/libphonenumber-js
> libphonenumber-generate-metadata metadata.min.json --extended

sh: 1: libphonenumber-generate-metadata: not found

npm ERR! Linux 3.13.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "libphonenumber-metadata"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! libphonenumber-js@0.4.1 libphonenumber-metadata: `libphonenumber-generate-metadata metadata.min.json --extended`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the libphonenumber-js@0.4.1 libphonenumber-metadata script 'libphonenumber-generate-metadata metadata.min.json --extended'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libphonenumber-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     libphonenumber-generate-metadata metadata.min.json --extended
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libphonenumber-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libphonenumber-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-03-29T23_04_03_471Z-debug.log
root@ip-172-31-5-150:/home/ubuntu/libphonenumber-js#`
```

**Comment by halt-hammerzeit** [comment]
Yes, it says:

```
sh: 1: libphonenumber-generate-metadata: not found
```

Which means exactly what it is: `libphonenumber-generate-metadata` executable is not found.

The readme says:


> First, add metadata generation script to your project's `package.json`

So, this npm script should be added to the project's  `package.json`, not to `libphonenumber-js`'s `package.json`.

**Comment by onlineautoparts** [comment]
Ok thanks for clearing that up. I'm using the **Standalone** version and I would like to use a custom metadata. I think it would be helpful to mention that in the README.

Is there a way I can customise the **Standalone version's metadata**?

**Comment by halt-hammerzeit** [comment]
Not understand your question

**Comment by onlineautoparts** [comment]
Sorry I've reworded my question, I hope is clear this time:

[EDITED]
Ok thanks for clearing that up. 

I'm using the **Standalone** version of libphonenumber (the one that does not use any bundlers). I'm calling libphonenumber using Javascript and JQuery for example:

`<script>
function validateNumber(value){
return libphonenumber.isValidNumber(value,$("#countryCode").val());
}
</script>`

I found that the phone number "23423423423" is valid in several countries. I would like to use the extended version of the metada at least for Australia and New Zealand.

Is there a way I can customise the **Libphonenumber Standalone version's metadata** and use the "browser-build" so that I can add to my website ?

**Comment by halt-hammerzeit** [comment]
For this case, follow the instructions in the Standalone section of the readme, and prior to building the bundle do:

```
npm run metadata:generate RU,US extended
```

See the `runnable/generate.js` file for reference.
That will probably work.
