### ISSUE TITLE
Return also country_phone_code from parse

### ISSUE THREAD

**Issue by jmustonen** [halt-hammerzeit/libphonenumber-js#63]
First of all, thanks for the nice library!

One small improvement came into my mind: why not return also `country_phone_code` from `parse()`, i.e. instead of:

```javascript
let parse = require('libphonenumber-js').parse
parse('+358401234567')
// { country: 'FI', phone: '401234567' }
parse('0401234567', 'FI')
// { country: 'FI', phone: '401234567' }
```

we'd get this:

```javascript
let parse = require('libphonenumber-js').parse
parse('+358401234567')
// { country: 'FI', phone: '401234567', country_phone_code: '358' }
parse('0401234567', 'FI')
// { country: 'FI', phone: '401234567', country_phone_code: '358' }
```

Ok, I am aware that you could do it with `asYouType`:

```javascript
let asYouType = require('libphonenumber-js').asYouType
let formatter = new asYouType()
formatter.input('+358401234567')
// '+358 40 1234567'
formatter.country
// 'FI'
formatter.country_phone_code
// '358'
formatter.national_number
// '401234567'
```

but for me it would make sense to include the `country_phone_code` also to `parse()` result.

If you feel this would be a welcome addition to the library, I'm more than happy to provide a pull request that would provide this functionality!

**Comment by halt-hammerzeit** [comment]
Why would one need `country_phone_code?

**Comment by halt-hammerzeit** [comment]
Country phone code can be obtained from `metadata` like `metadata.countries.RU[0]`

**Comment by jmustonen** [comment]
As to why: we have phone numbers in the `'+358401234567'` format available, and we need to split them to a `{countryCode: '358', phoneNumber: '401234567'}` format, to be used in another place. Thus, it would have been _convenient_ to just require `parse` from the library, call `parse()` with the existing phone number, and get all the needed stuff directly from the result.

Ok, it's also easy to get the country code from `metadata` as you said, with one additional require, so if you feel like this is an unnecessary addition to the library, so be it.

**Comment by halt-hammerzeit** [comment]
It would have been a second require anyway because I don't see any benefit of returning country phone code from parse because it's redundant data.
I would also suggest you store your phone numbers with `country` instead of `countryCode` because I see no justification for any further `countryCode` usage.

**Comment by halt-hammerzeit** [comment]
Use `getPhoneCode()` of the new version `libphonenumber-js@0.4.5`

**Comment by catamphetamine** [comment]
FYI: the latest version returns `countryCallingCode` when parsing with `extended: true` flag.
See the demo.
https://catamphetamine.github.io/libphonenumber-js/
