### ISSUE TITLE
Need method to get Country Code by Country Name

### ISSUE THREAD

**Issue by Sundarasan** [halt-hammerzeit/libphonenumber-js#64]
It would be great if we can get country code based on country name.

Something like this.
```javascript
getCountryCode('US');  // +1
```

**Comment by halt-hammerzeit** [comment]
Why would you need that

**Comment by Sundarasan** [comment]
In my application, I know the country from where the user is coming from, so I would like to pre-fill his country code while prompting for phone number.

Just now read other issues.
https://github.com/halt-hammerzeit/libphonenumber-js/issues/63#issuecomment-290646021
How do I access metadata. Is `metadata` exposed?

**Comment by halt-hammerzeit** [comment]
Use `getPhoneCode()` of the new version `libphonenumber-js@0.4.5`

**Comment by Sundarasan** [comment]
@halt-hammerzeit: Thanks! That was a blazing fast release. 👍 
It would be great if you can update this in `README.md` file as well, so that people wouldn't bug you.

**Comment by yuliankarapetkov** [comment]
Use `getCountryCallingCode()`:

> Returns country calling code for a country. Will throw an error if country doesn't exist or isn't supported by this library.

```
import { getCountryCallingCode } from 'libphonenumber-js';

getCountryCallingCode('RU') === '7'
getCountryCallingCode('IL') === '972'
```
