### ISSUE TITLE
Invalid phone number when it should be valid

### ISSUE THREAD

**Issue by onlineautoparts** [halt-hammerzeit/libphonenumber-js#67]
Hello, 

I was running tests with australian numbers when I found that "413071810" is not valid if there's no "0" before it i.e. "0413071810"

I verified that Google's Javascript demo does recognize "413071810" as a valid number for Australia(AU) https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html 

In Australia is normal to use "04" or "4" for mobile numbers. Also Safari autofill feature adds Australian mobile numbers without the zero that's how I found this problem.

**Comment by halt-hammerzeit** [comment]
I had a look at your case and Google's demo indeed says that this is a valid number.
I personally think Google's algorythm is wrong and if `0` is really not required then you may create an issue in their repo to add `nationalPrefixOptionalWhenFormatting="true"` either to the format itself to to the whole AU country.
https://github.com/googlei18n/libphonenumber/blob/3894ee185c277ee5d0c9e81993030aaaff4a8d50/resources/PhoneNumberMetadata.xml#L1725-L1732

**Comment by onlineautoparts** [comment]
Thank you for having a look at this. I believe the issue stills falls under this repository because even in their metadata they show "412345678" as an example for a mobile number.

https://github.com/googlei18n/libphonenumber/blob/3894ee185c277ee5d0c9e81993030aaaff4a8d50/resources/PhoneNumberMetadata.xml#L1848 

Do you know of a way I can manually make it work for Australia? Almost 90% of our users will be Australian.

**Comment by halt-hammerzeit** [comment]
Well, we can make it this way:

1. You create an issue in Google's repo describing that `nationalPrefixOptionalWhenFormatting` should be `true` for either this exact phone number format or for Australia as a whole.
2. We see how they clarify the situation and whether they recognize this bug.
3. Depends on 1. and 2.

**Comment by onlineautoparts** [comment]
Thanks for your help. For reference I've created this issue in Google's repo: https://github.com/googlei18n/libphonenumber/issues/1696

**Comment by halt-hammerzeit** [comment]
Yeah, I saw it.
Either they add that parameter to the metadata or I add that parameter manually as a workaround specially for Australia.

**Comment by halt-hammerzeit** [comment]
Fixed in the new version
