### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by code-chris** [halt-hammerzeit/libphonenumber-js#68]
Hi @halt-hammerzeit,
first, thank you that you are working on this library!!

I've some questions to you:
- The files inside `source/tools` seems to be helper scripts and not part of the library at runtime, right?
- This means that "bluebird", "minimist" and "xml2js" should be `devDependencies`?
- Do you think, that there's a way that babel-runtime does not become a runtime dependency? (I use this lib in a typescript project without any dependencies to babel)
- Is it possible to split the `metadata.min.json` to single json files for each supported language to reduce the bundle size in projects which use this library?

General:
- `bin/update-metadata.js` and the contents of `runnable` seems to be helper scripts too?
- There are different `Promise` implementations used (native in download.js, Bluebird in generate.js)

Thanks!!

**Comment by halt-hammerzeit** [comment]
> The files inside source/tools seems to be helper scripts and not part of the library at runtime, right?

That's metadata generator

> This means that "bluebird", "minimist" and "xml2js" should be devDependencies?

A developer can install this library and then generate his own metadata meaning that `devDependencies` are still required in 3rd party projects. There's no difference I can see between `devDependencies` and `dependencies` rather than taking some extra kilobytes on a machine

> Do you think, that there's a way that babel-runtime does not become a runtime dependency? (I use this lib in a typescript project without any dependencies to babel)

Don't understand

> Is it possible to split the metadata.min.json to single json files for each supported language to reduce the bundle size in projects which use this library?

See "custom metadata" section

> bin/update-metadata.js and the contents of runnable seems to be helper scripts too?

Yes

> There are different Promise implementations used (native in download.js, Bluebird in generate.js)

Not a question

**Comment by code-chris** [comment]
- Some extra kilobytes on a dev machine are not a problem, I agree. But depending on the bundler used in the project which uses this library, the dependencies maybe are included by default. And in production build of a software it is important to reduce the bundles as much as possible.
- `babel-runtime` is only a proxy of `core-js` which is pretty huge. That means that I have to include `core-js` only for a few functions which I do not need anywhere else in my app..... Maybe there's a way to replace this peaces of code with other (native) constructs to make `babel-runtime` and `core-js` gratuitous.
- Different promises: This was not a question indeed, only a statement.

**Comment by halt-hammerzeit** [comment]
> Some extra kilobytes on a dev machine are not a problem, I agree. But depending on the bundler used in the project which uses this library, the dependencies maybe are included by default. And in production build of a software it is important to reduce the bundles as much as possible.

I don't see how a bundler would include those extra kilobytes of modules

> That means that I have to include core-js only for a few functions which I do not need anywhere else in my app

That is true, the code is compiled using babel and `babel-plugin-runtime-transform` as it is [recommended in babel docs](http://babeljs.io/docs/plugins/transform-runtime/).
It does take a lot of space but usually the project itself uses Babel in the form of `babel-polyfill` which [is based on `core-js`](https://babeljs.io/docs/usage/polyfill/), therefore `core-js` is included either way.

**Comment by code-chris** [comment]
Yes, it is recommended for babel projects. But as I said in my first post, my project does not work with babel and core-js is not already included.

**Comment by halt-hammerzeit** [comment]
So your code is ES5 then.
Well, maybe this all could be more efficient but I have no experience in minimizing `babel-runtime` impact.
Polyfills are not an option because they modify global variables.
Maybe it could be rewritten without `babel-runtime`.
You can try experimenting with it if you want to.

**Comment by code-chris** [comment]
No, it's not ES5, but TypeScript. Yes, maybe I give it a try.
