### ISSUE TITLE
Country names

### ISSUE THREAD

**Issue by santhosh-rajashekar** [halt-hammerzeit/libphonenumber-js#69]
do we get the country names along with the country codes?

**Comment by halt-hammerzeit** [comment]
There's no such thing as a "country name" because it is locale-specific.

**Comment by santhosh-rajashekar** [comment]
I mean, in my application i would like display country names for example
Germany (+49) ...something like that.

is it possible to include such a possibility?

**Comment by halt-hammerzeit** [comment]
This library does not provide country name localization.

**Comment by santhosh-rajashekar** [comment]
any suggestions, if the original library support such a feature out of the box?

**Comment by halt-hammerzeit** [comment]
Google's libphonenumber doesn't support that kind of feature so this port does not also.
