### ISSUE TITLE
libphonenumber.isValidNumber not wirking as expected

### ISSUE THREAD

**Issue by santhosh-rajashekar** [halt-hammerzeit/libphonenumber-js#71]
libphonenumber.isValidNumber(mobile_number, country_code) returns true for invalid numbers as well.

For example, i enetered 
country_code - DE
mobile number : 1755892292222222222
function returns true as a result, is there something wrong in the library?

**Comment by halt-hammerzeit** [comment]
Does the Google's demo give `false`?

**Comment by santhosh-rajashekar** [comment]
could you please send me the link to google demo, which you are referring to.

**Comment by halt-hammerzeit** [comment]
https://github.com/halt-hammerzeit/libphonenumber-js#bug-reporting
