### ISSUE TITLE
libphonenumber-metadata not so clear

### ISSUE THREAD

**Issue by santhosh-rajashekar** [halt-hammerzeit/libphonenumber-js#72]
{
  "scripts": {
    "libphonenumber-metadata": "libphonenumber-generate-metadata metadata.min.json --countries RU,DE --extended",
  }
}

when we add the script to package.json and run the command as explained, there is an error it is not generating the json with extended data

**Comment by halt-hammerzeit** [comment]
Paste the error

**Comment by santhosh-rajashekar** [comment]
got it working, i was doing a mistake.
i was modifying the package.json in the fork project instead of my project where added this module
