### ISSUE TITLE
Leading zero doesn't get removed by the format function

### ISSUE THREAD

**Issue by JonasSeegers** [halt-hammerzeit/libphonenumber-js#77]
As the title says, if you call the function like this
`format(017212345678, 'DE', 'International_plaintext');`
you'll receive the number as `+49017212345678 ` although it should be `+4917212345678`

**Comment by halt-hammerzeit** [comment]
I updated the readme to reflect the right usage of `format()`.
https://github.com/halt-hammerzeit/libphonenumber-js/commit/c089c959838924c97227cc2dca9c995109161b1e
First one should `parse()` the phone number and only then it can be `format()`ted.
