### ISSUE TITLE
Question: Is it possible to specify that you only want mobile numbers (without loading all other types via extend)?

### ISSUE THREAD

**Issue by Rob1080** [halt-hammerzeit/libphonenumber-js#78]
Hi,

I'd like to only accept mobile numbers as input.
In the old libphonenumber code, I was checking through all the types, and only accepting the number if it was a mobile number. I could do the same with your library, but as you say, the resulting file size is considerably bigger if you want to support "number types".
My question is whether the library could be extended to to generate the metadata only for mobile number types, e.g. with flags as follows: --countries DE --number_types mobile
Then when parsing a number, and calling get_number_type, non-mobile numbers would report a type of "unknown" and valid mobile numbers would return type "mobile". I would assume there would be a size saving over using --extended option (which supports all phone number types). 

If you have advice on how to achieve this, it would be greatly appreciated.

Thanks
Rob

**Comment by halt-hammerzeit** [comment]
https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/source/get%20number%20type.js
Theoretically you could post-process the resulting `metadata.json` to only have the `mobile` regular expression.
(`[1]` in the array)
https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/source/tools/compress.js
You could test that and see if it works

**Comment by Rob1080** [comment]
ok, thanks, will give it a go.

**Comment by halt-hammerzeit** [comment]
I released the new version which comes prepackaged with `metadata.mobile.json` and also supports the new `--types` flag for metadata generation.
Seems to work.
