### ISSUE TITLE
npm metadata:update script broken

### ISSUE THREAD

**Issue by st-andrew** [halt-hammerzeit/libphonenumber-js#82]
As per the [instructions](https://github.com/halt-hammerzeit/libphonenumber-js#metadata) in the README to update the Metadata from Google's repo, I executed 
```bash
$ npm run metadata:update
```
This downloaded the latest XML file but the script failed when it checked how many files had been modified.  See [here](https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/runnable/update.js#L51).

The problem is that the [update.js](https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/runnable/update.js#L31) script executes [metadata:generate](https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/package.json#L36) which regenerates all the metadata files including min, full, and mobile. So when `update.js` [checks](https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/runnable/update.js#L44) how many files have been modified, it fails because too many have been changed.

The way I see it, there's 2 ways to fix this depending on what the intent of the `update.js` script is.
- If ALL the metadata files should be regenerated then `update.js` should be updated to expect at most 4 files to be changed
  - PhoneNumberMetadata.xml
  - metadata.full.json
  - metadata.min.json
  - metadata.mobile.json

- If only the XML and min metadata files should be updated then `update.js` should execute `metadata:generate:min` instead.

I don't mind submitting a PR with either one of these changes, just let me know which one it should be.

**Comment by halt-hammerzeit** [comment]
Oooh, thx, good catch.
Fixed.
