### ISSUE TITLE
UK National 03xxxxxxx landline not valid

### ISSUE THREAD

**Issue by bengesoff** [halt-hammerzeit/libphonenumber-js#88]
Tried to run this number through the parser and it is supposedly invalid however the google libphonenumber demo says it's ok: 03300 881288. Just to confirm, it is a valid phone number :) Interestingly, replacing the 03 with +443 satisfies the parser.

**Comment by halt-hammerzeit** [comment]
> it is supposedly invalid

Be more specific

**Comment by halt-hammerzeit** [comment]
`03300881288` `GB` demo parses the number as a valid one

**Comment by bengesoff** [comment]
My bad, sorry, was looking at the "as you type" validity check
