### ISSUE TITLE
asYouType incorrectly formats some NZ numbers

### ISSUE THREAD

**Issue by aryo** [halt-hammerzeit/libphonenumber-js#89]
The as-you-type formatter could return incorrect values for inputs with less than 5 digits.

`new asYouType("NZ").input("0212")` returns `02-12`, which is incorrect as there is no 02 area code in NZ. Should return `021 2`.

`new asYouType("NZ").input("02122")` returns `021 22`, which is correct

Whereas google's as-you-type formatter will correctly return `021 2`.

See https://en.wikipedia.org/wiki/List_of_dialling_codes_in_New_Zealand

Edit: similar thing happens when inputting `+64212`; returns `+64 2 12`, when it should be `+64 21 2`

**Comment by halt-hammerzeit** [comment]
Fixed in the latest release
