### ISSUE TITLE
Metadata loading fails

### ISSUE THREAD

**Issue by MarkoSulamagi** [halt-hammerzeit/libphonenumber-js#9]
I'm trying to load the library like this: `import { parse, format } from 'libphonenumber-js';` and gives me an error during build.

```
ERROR in ./~/libphonenumber-js/metadata.min.json
Module parse failed: ./node_modules/libphonenumber-js/metadata.min.json Unexpected token (1:34)
You may need an appropriate loader to handle this file type.
```

I'm using ES6+, babel and Vue 2 with Laravel as framework

**Comment by halt-hammerzeit** [comment]
It tells you what to do:

> ERROR in ./~/libphonenumber-js/metadata.min.json
> You may need an appropriate loader to handle this file type.

Now tell me what do you need to do to make it work

**Comment by MarkoSulamagi** [comment]
I needed to include json-loader with my webpack configuration.
Thanks for pushing me, I should've thought of that.

**Comment by halt-hammerzeit** [comment]
@MarkoSulamagi Yeah, it's described in the end of the README but not everyone gets there
