### ISSUE TITLE
Issue with Reunion

### ISSUE THREAD

**Issue by nicolasvahidzein** [halt-hammerzeit/libphonenumber-js#91]
Hello again,

i hope i am not doing anything wrong, but i see nothing for reunion in 262 country code, is the issue just on my side?

**Comment by halt-hammerzeit** [comment]
Explain in more detail

**Comment by nicolasvahidzein** [comment]
It's just not recognizing reunion at all, i try this and any other 262 number but it's not working: +262445566

all the other numbers work, strange. Any idea?

**Comment by halt-hammerzeit** [comment]
Still not clear.
Describe the steps of reproducing the situation, the actual outcome, the desired outcome and whether Google's demo gives the desired result.

**Comment by nicolasvahidzein** [comment]
My apologies Halt, i was not inputing an actual real number and i was somehow not validating some of the many rules for that number and so it was not recognizing it as valid nor displaying the territory.

For la Reunion +262 was not enough, for it to recognize la reunion at all it has to be +262-262 and then some more numbers.

I'm closing the ticket and thanks for your time.
